// The eight playable fighters. Each has a unique `special` ability that is
// resolved by the engine in game.js (see `spawnSpecial` / `startSpecial`).
export const CHARACTERS = [
  {
    id: 'blaze',
    name: 'Blaze',
    title: 'Ember Fist',
    color: '#ff5a1f',
    accent: '#ffd166',
    hp: 100,
    speed: 1.0,
    power: 1.0,
    special: 'fireball',
    specialName: 'Fireball',
    specialCost: 1.2,
    blurb: 'Hurls a searing orb across the stage.',
  },
  {
    id: 'frost',
    name: 'Frost',
    title: 'Glacier Guard',
    color: '#38bdf8',
    accent: '#e0f2fe',
    hp: 115,
    speed: 0.9,
    power: 1.0,
    special: 'ice',
    specialName: 'Ice Shard',
    specialCost: 1.4,
    blurb: 'Freezes foes solid with a chilling shard.',
  },
  {
    id: 'volt',
    name: 'Volt',
    title: 'Storm Runner',
    color: '#facc15',
    accent: '#fff7cc',
    hp: 90,
    speed: 1.25,
    power: 0.95,
    special: 'dash',
    specialName: 'Thunder Dash',
    specialCost: 1.3,
    blurb: 'Blitzes forward in a crackling instant strike.',
  },
  {
    id: 'titan',
    name: 'Titan',
    title: 'Iron Colossus',
    color: '#b45309',
    accent: '#fde68a',
    hp: 130,
    speed: 0.78,
    power: 1.15,
    special: 'slam',
    specialName: 'Quake Slam',
    specialCost: 2.0,
    blurb: 'Shakes the ground with an armored shockwave.',
  },
  {
    id: 'shadow',
    name: 'Shadow',
    title: 'Silent Blade',
    color: '#7c3aed',
    accent: '#c4b5fd',
    hp: 95,
    speed: 1.15,
    power: 1.05,
    special: 'teleport',
    specialName: 'Shadow Step',
    specialCost: 1.5,
    blurb: 'Vanishes and reappears behind the enemy.',
  },
  {
    id: 'verdant',
    name: 'Verdant',
    title: 'Life Bloom',
    color: '#16a34a',
    accent: '#bbf7d0',
    hp: 120,
    speed: 0.95,
    power: 0.9,
    special: 'heal',
    specialName: 'Bloom',
    specialCost: 5.0,
    blurb: 'Restores health with a surge of living energy.',
  },
  {
    id: 'boulder',
    name: 'Boulder',
    title: 'Stone Breaker',
    color: '#78716c',
    accent: '#d6d3d1',
    hp: 125,
    speed: 0.85,
    power: 1.1,
    special: 'rock',
    specialName: 'Rock Toss',
    specialCost: 1.6,
    blurb: 'Lobs a heavy boulder that stuns on impact.',
  },
  {
    id: 'storm',
    name: 'Storm',
    title: 'Gale Dancer',
    color: '#0ea5e9',
    accent: '#bae6fd',
    hp: 100,
    speed: 1.1,
    power: 1.0,
    special: 'gust',
    specialName: 'Gale Burst',
    specialCost: 1.4,
    blurb: 'Unleashes a fan of wind blades that shove foes back.',
  },
];

export const getCharacter = (id) => CHARACTERS.find((c) => c.id === id) || CHARACTERS[0];
